export let cards = {
    "A_clubs": 1,
    "2_clubs": 1,
    "3_clubs": 1,
    "4_clubs": 1,
    "5_clubs": 1,
    "6_clubs": 1,
    "7_clubs": 1,
    "8_clubs": 1,
    "9_clubs": 1,
    "10_clubs": 1,
    "J_clubs": 1,
    "Q_clubs": 1,
    "K_clubs": 1,

    "A_diamonds": 1,
    "2_diamonds": 1,
    "3_diamonds": 1,
    "4_diamonds": 1,
    "5_diamonds": 1,
    "6_diamonds": 1,
    "7_diamonds": 1,
    "8_diamonds": 1,
    "9_diamonds": 1,
    "10_diamonds": 1,
    "J_diamonds": 1,
    "Q_diamonds": 1,
    "K_diamonds": 1,

    "A_hearts": 1,
    "2_hearts": 1,
    "3_hearts": 1,
    "4_hearts": 1,
    "5_hearts": 1,
    "6_hearts": 1,
    "7_hearts": 1,
    "8_hearts": 1,
    "9_hearts": 1,
    "10_hearts": 1,
    "J_hearts": 1,
    "Q_hearts": 1,
    "K_hearts": 1,

    "A_spades": 1,
    "2_spades": 1,
    "3_spades": 1,
    "4_spades": 1,
    "5_spades": 1,
    "6_spades": 1,
    "7_spades": 1,
    "8_spades": 1,
    "9_spades": 1,
    "10_spades": 1,
    "J_spades": 1,
    "Q_spades": 1,
    "K_spades": 1
}